### ISSUE TITLE
Adding a new Geo2Grid product to the *yaml files?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#349]
Hello, all -- 

1.)  We are trying to create a new Geo2Grid composite product, and came across an error message that we do not understand (yaml.composer.ComposerError: found undefined alias 'stretchfun').   We are running 1.0.2.  I have included below the commandline, the contents of our core composites/abi.yaml and enhancements/generic.yaml     Any ideas?   Thank you!

2.)  Do you know when the next iteration of Geo2Grid is supposed to be released?   Perhaps Section 5 of the User's Guide (Composites) could be expanded a bit.   For example, what options exist for compositor?   And some documentation on 
enhancements would also be good.  For example,  is there a way to find out what various stretch methods are available?

Thank you very much for any help you can provide!

Sincerely,

Jim

The commandline:

```
export PYTROLL_CHUNK_SIZE="4096" ; geo2grid.sh  -r  abi_l1b  -w  geotiff  -p  c02_c07_c08  -g  eastern_us --grid-configs  geo2grid_config.conf  -f /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C01_G16_s20180602202007_e20180602202065_c20180602202107.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C02_G16_s20180602202007_e20180602202064_c20180602202097.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C03_G16_s20180602202007_e20180602202065_c20180602202111.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C04_G16_s20180602202007_e20180602202065_c20180602202098.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C05_G16_s20180602202007_e20180602202065_c20180602202107.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C06_G16_s20180602202007_e20180602202071_c20180602202103.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C07_G16_s20180602202007_e20180602202077_c20180602202101.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C08_G16_s20180602202007_e20180602202064_c20180602202101.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C09_G16_s20180602202007_e20180602202070_c20180602202101.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C10_G16_s20180602202007_e20180602202076_c20180602202100.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C11_G16_s20180602202007_e20180602202065_c20180602202100.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C12_G16_s20180602202007_e20180602202070_c20180602202101.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C13_G16_s20180602202007_e20180602202076_c20180602202104.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C14_G16_s20180602202007_e20180602202065_c20180602202103.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C15_G16_s20180602202007_e20180602202071_c20180602202102.nc /arcdata/goes/grb/goes16/2018/2018_03_01_060/abi/L1b/RadM2/OR_ABI-L1b-RadM2-M3C16_G16_s20180602202007_e20180602202076_c20180602202103.nc  --radius-of-influence 50000  --output-filename  GOES-16_ABI_RadM2_c02_c07_c08_2018060_220200Z.tif
```

The error message:   `yaml.composer.ComposerError: found undefined alias 'stretchfun'`

Within the file  composites/abi.yaml:

```
c02_c07_c08:
    description: >
      Plume RGB, for GOESR: NASA, NOAA
#   references:
#     None, created by T. J. Schmit
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
      - name: C02 
      - name: C07 
      - name: C08 
    standard_name: c02_c07_c08
```

Within the file  enhancements/generic.yaml:

```
c02_c07_c08_default:
    standard_name: c02_c07_c08
    operations:
    - name: stretch
      method: *stretchfun
      kwargs:
        stretch: crude
        min_stretch: [0, 0, 0]
        max_stretch: [100, 70, 30] 
    - name: gamma
      method: *gammafun
      kwargs:
        gamma: [1.0, 1.0, 1.0]
```
