### ISSUE TITLE
A question on Geo2Grid gamma correction

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#356]
Hello, all -- We are working on implementing a Fire RGB within Geo2Grid, and are having some difficulties with implementing the gamma correction.  It doesn't seem like geo2grid.sh is "seeing" the gamma correction that we wish to make.  We're also having problems getting the desired crude stretches to take effect.  I suspect we are doing something wrong, but we don't know what that is.  We are using Geo2Grid version 1.0.2. 

1.) Here is what we have in our satpy/enhancements/abi.yaml file:

```
   fire_temperature_default:
    standard_name: fire_temperature
    operations:
    - name: stretch
      method: !!python/name:satpy.enhancements.stretch
      kwargs:
        stretch: crude
        min_stretch: [273,   0,  0]  
        max_stretch: [333, 100, 75] 
    - name: gamma
      method: !!python/name:satpy.enhancements.gamma
      kwargs:
        gamma: [0.4, 1.0, 1.0]
```

2.) Here is what we have in our satpy/composites/abi.yaml file:

```
    fire_temperature:
    description: >
      Fire Temperaure, for GOESR: NASA, NOAA
#   references:
#     See Quick Guide
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
      - name: C07 
      - name: C06 
      - name: C05 
    standard_name: fire_temperature
```

3.) Here is our geo2grid.sh commandline:

```
export PYTROLL_CHUNK_SIZE="4096" ; geo2grid.sh -r abi_l1b -w geotiff -p fire_temperature -g eastern_us --grid-configs geo2grid_config.conf -f /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C01_G17_s20211611800255_e20211611800313_c20211611800342.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C02_G17_s20211611800255_e20211611800313_c20211611800332.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C03_G17_s20211611800255_e20211611800313_c20211611800339.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C04_G17_s20211611800255_e20211611800313_c20211611800337.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C05_G17_s20211611800255_e20211611800313_c20211611800344.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C06_G17_s20211611800255_e20211611800318_c20211611800346.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C07_G17_s20211611800255_e20211611800324_c20211611800354.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C08_G17_s20211611800255_e20211611800313_c20211611800352.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C09_G17_s20211611800255_e20211611800318_c20211611800356.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C10_G17_s20211611800255_e20211611800324_c20211611800364.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C11_G17_s20211611800255_e20211611800313_c20211611800350.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C12_G17_s20211611800255_e20211611800318_c20211611800368.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C13_G17_s20211611800255_e20211611800324_c20211611800358.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C14_G17_s20211611800255_e20211611800313_c20211611800360.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C15_G17_s20211611800255_e20211611800318_c20211611800366.nc /arcdata/goes/grb/goes17/2021/2021_06_10_161/abi/L1b/RadM1/OR_ABI-L1b-RadM1-M6C16_G17_s20211611800255_e20211611800324_c20211611800354.nc --radius-of-influence 50000 --output-filename GOES-17_ABI_RadM1_fire_temperature_2021161_180025Z.tif
```

4.) Here is some of the output stored within the logfile:   abi_l1b_geotiff_20210610_180025.log    This is the only verbiage that discusses gamma within this logfile:

```
[2021-06-11 14:15:36,865] : PID  30870 : DEBUG    : satpy.writers : apply : Enhancement configuration options: [{'name': 'stretch', 'method': <function stretch at 0x7f87381eef80>, 'kwargs': {'stretch': 'crude', 'min_stretch': [0, 0, 0], 'max_stretch': [3.5, 35.0, 85.0]}}, {'name': 'gamma', 'method': <function gamma at 0x7f87316c88c0>, 'kwargs': {'gamma': [1.0, 1.0, 1.0]}}]
[2021-06-11 14:15:36,865] : PID  30870 : DEBUG    : trollimage.xrimage : stretch : Applying stretch crude with parameters {'min_stretch': [0, 0, 0], 'max_stretch': [3.5, 35.0, 85.0]}
[2021-06-11 14:15:36,871] : PID  30870 : DEBUG    : trollimage.xrimage : gamma : Applying gamma <xarray.DataArray (bands: 3)>
array([1., 1., 1.]) 
Coordinates:
  * bands    (bands) <U1 'R' 'G' 'B'
[2021-06-11 14:15:36,896] : PID  30870 : INFO     : abi_l1b_geotiff : main : Computing products and saving data to writers...
[2021-06-11 14:15:38,774] : PID  30870 : INFO     : abi_l1b_geotiff : main : SUCCESS
```

5.)  Questions
      a.)  There is no verbiage in the logfile describing our desired gamma correction of [0.4,1.0,1.0]    The only gamma correction noted in the logfile is [1.0, 1.0, 1.0]   Furthermore, it does not matter if I change the gamma specified in enhancements/abi.yaml -- The only gamma ever being applied appears to be the [1.0, 1.0, 1.0] correction.
      b.)  It appears also that the desired min/max enhancement stretches are not being used.  We do not see the desired min/max  stretch bounds of  min_stretch: [273,   0,  0]   max_stretch: [333, 100, 75]  being applied -- only the min_stretch: [0,   0,  0]  
        max_stretch: [3.5, 35.0, 85.0] 

We're not sure what we are doing wrong.   So any help you can provide would be much appreciated!

Thank you very much!

Sincerely,

Jim
