### ISSUE TITLE
Add Normalized Burn Ratio (NBR) composite example

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#542]
Sam Batzli would like to use an NBR composite. Rather than having to compute it from floating point or 16-bit geotiffs, it may be better to compute it as a Satpy composite by configuring it in a YAML configuration file. Here's my attempt.

Definition: `nbr = (nir - swir) / (nir + swir)`

YAML to put in `etc/composites/viirs.yaml`:

```yaml
  nbr:
    compositor: !!python/name:satpy.composites.viirs.GenericCompositor
    prerequisites:
      - compositor: !!python/name:satpy.composites.RatioCompositor
        prerequisites:
          - compositor: !!python/name:satpy.composites.DifferenceCompositor
            prerequisites:
              - name: M11
              - name: M07
          - compositor: !!python/name:satpy.composites.SumCompositor
            prerequisites:
              - name: M11
              - name: M07
    standard_name: normalized_burn_ratio
```

Produces:

![image](https://user-images.githubusercontent.com/1828519/195864142-c62bf484-975d-41e5-876b-9f89e658e4c1.png)

Note: This is dynamically linearly scaled. I'm sure there is something else people would expect.
